---
title: "Obesity among adults by country, 1975-2016"
author: Maxim Fominykh, Arseny Anciferov
date: 5/16/20
output: pdf_document
---
# Anomaly detection

```{r,results='hide', message=F, warning=F}
library(dplyr)
library(tidyr)
library(plyr)
library(anomalize)
library(tibble)
library(tibbletime)
library(ggplot2)
library(cowplot)
library(gridExtra)
library(purrr)
```


```{r}
# Load data
df = read.csv("obesity-cleaned.csv")
df[sample(nrow(df), 15),]
```

```{r}
# Replace column names
names(df) = c('id', 'name', 'year', 'obesity', 'sex')
# Filter No data
df = df %>% filter(obesity != 'No data')

# Clean obesity column and convert to float
df = df %>%
  separate("obesity", "obesity", sep = " ", remove = TRUE, convert = TRUE) %>%
  transform(obesity = as.double(obesity)) %>%
  mutate(date = as.Date(ISOdate(year, 1, 1)))
df[sample(nrow(df), 15),]
```

```{r}
# List of countries and sexes to analyze
countries = c("United States", "Russian Federation", "Ghana")
sexes = list("Both sexes", "Male", "Female")

# List of output plots
plots = list()
i = 1
```


```{r,results='hide', message=F, warning=F}
for (c in countries) {
  for (s in sexes) {
    df_country_sex = df %>% filter(name == c & sex == s)

    df_obesity = df_country_sex %>%
      as_tbl_time(index = date) %>%
      as_period("yearly")

    tdf_obesity = df_obesity %>%
      time_decompose(obesity) %>%
      anomalize(remainder) %>%
      time_recompose() %>%
      plot_anomalies(time_recomposed = TRUE, alpha_dots = 1, color_no = "#228B22", color_yes = "red") +
      labs(title = c, subtitle = s) +
      xlab("Year") +
      ylab("Obesity %")
    plots[[i]] = tdf_obesity
    i = i + 1
  }
}
```

```{r,fig.width=25, fig.height=14}
# Display plots in 3 rows and 3 cols
f = partial(grid.arrange, ncol = 3, nrow = 3)
q = do.call(f, plots)
```

# Geospatial plots
```{r,results='hide', message=F, warning=F}
library(dplyr)
library(tidyr)
library(sf)
library(spData)
library(plyr)
library(ggplot2)
library(tidyverse)
library(ggplotify)
library(gridExtra)
```

```{r}
df = read.csv("obesity-cleaned.csv")
# Replace column names
names(df) = c('id', 'name_long', 'year', 'obesity', 'sex')


# Filter No data
df = df %>% filter(obesity != 'No data')

# Clean obesity column and convert to float
df = df %>%
  separate("obesity", "obesity", sep = " ", remove = TRUE, convert = TRUE) %>%
  transform(obesity = as.double(obesity)) %>%
  mutate(date = as.Date(ISOdate(year, 1, 1)))
df[sample(nrow(df), 15),]
```


```{r}
# Merge with world geo data
df_with_countries = merge(world, df, by = "name_long")

df_with_countries[sample(nrow(df_with_countries), 15),]
```

```{r,fig.width=25, fig.height=14}

# List of sexes and years to plot
sexes = c("Male", "Female", "Both sexes")
years = c(1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015)
plots = list()
i = 1
for (year in years) {
  for (s in sexes) {
    df1 = df_with_countries %>%
      filter(year == year & sex == s) %>%
      select(obesity)
    # convert sf to ggplot to display in grid
    df2 = ggplot(df1) +
      geom_sf(aes(fill = obesity)) +
      theme(panel.background = element_rect(fill = 'azure'), legend.position = "bottom") +
      scale_fill_gradientn(colours = heat.colors(10, rev = TRUE)) +
      labs(title = sprintf("%d Obesity %%", year), subtitle = s)
    plots[[i]] = df2
    i = i + 1
  }
}

f = partial(grid.arrange, ncol = 3, nrow = 3)
do.call(f, plots[1:9])
```

```{r,fig.width=25, fig.height=14}
do.call(f, plots[10:18])
```
```{r,fig.width=25, fig.height=14}
do.call(f, plots[19:27])
```


